[package]
name = "solidus-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
ed25519-dalek.workspace = true
blake3.workspace = true
rand.workspace = true
serde.workspace = true
bs58.workspace = true
hex.workspace = true
thiserror.workspace = true
blst.workspace = true
sha2.workspace = true
