use serde::Deserialize;
use std::path::{Path, PathBuf};

/// Multi-node configuration, parsed from the TOML files generated by the
/// `genesis` CLI command (Task 11).
///
/// Each validator directory gets a `config.toml` with a `[node]` section and
/// zero or more `[[peers]]` entries.
#[derive(Debug, Deserialize)]
pub struct MultiNodeConfig {
    pub node: NodeSection,
    #[serde(default)]
    pub peers: Vec<PeerSection>,
}

/// The `[node]` section of a multi-node config.
#[derive(Debug, Deserialize)]
pub struct NodeSection {
    /// Chain identifier (must match genesis.json).
    pub chain_id: String,
    /// TCP port for P2P consensus communication.
    pub listen_port: u16,
    /// Directory where RocksDB and other persistent data are stored.
    pub data_dir: PathBuf,
    /// Path to the genesis.json file (relative or absolute).
    pub genesis: PathBuf,
    /// Path to the Ed25519 secret key file (hex-encoded, 32 bytes).
    pub ed25519_key: PathBuf,
    /// Path to the BLS12-381 secret key file (hex-encoded, 32 bytes).
    pub bls_key: PathBuf,
    /// TCP port for the JSON-RPC server.
    pub rpc_port: u16,
    /// This validator's zero-based index in the committee.
    pub node_index: usize,
}

/// A `[[peers]]` entry describing a known validator peer.
///
/// Fields are read during deserialization and will be consumed when wiring up
/// the libp2p transport in production mode.
#[derive(Debug, Deserialize)]
#[allow(dead_code)]
pub struct PeerSection {
    /// The peer's zero-based index in the committee.
    pub index: usize,
    /// The peer's address (e.g. `"127.0.0.1:30301"`).
    pub address: String,
}

impl MultiNodeConfig {
    /// Load a `MultiNodeConfig` from a TOML file at the given path.
    pub fn from_file(path: &Path) -> Result<Self, Box<dyn std::error::Error>> {
        let content = std::fs::read_to_string(path)?;
        Ok(toml::from_str(&content)?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_minimal_config() {
        let toml_str = r#"
[node]
chain_id = "solidus-testnet-1"
listen_port = 30300
data_dir = "./data"
genesis = "../genesis.json"
ed25519_key = "node.key"
bls_key = "bls.key"
rpc_port = 8080
node_index = 0
"#;

        let cfg: MultiNodeConfig = toml::from_str(toml_str).expect("parse failed");
        assert_eq!(cfg.node.chain_id, "solidus-testnet-1");
        assert_eq!(cfg.node.listen_port, 30300);
        assert_eq!(cfg.node.node_index, 0);
        assert_eq!(cfg.node.rpc_port, 8080);
        assert!(cfg.peers.is_empty());
    }

    #[test]
    fn parse_config_with_peers() {
        let toml_str = r#"
[node]
chain_id = "solidus-testnet-1"
listen_port = 30300
data_dir = "./data"
genesis = "../genesis.json"
ed25519_key = "node.key"
bls_key = "bls.key"
rpc_port = 8080
node_index = 0

[[peers]]
index = 1
address = "127.0.0.1:30301"

[[peers]]
index = 2
address = "127.0.0.1:30302"

[[peers]]
index = 3
address = "127.0.0.1:30303"
"#;

        let cfg: MultiNodeConfig = toml::from_str(toml_str).expect("parse failed");
        assert_eq!(cfg.peers.len(), 3);
        assert_eq!(cfg.peers[0].index, 1);
        assert_eq!(cfg.peers[0].address, "127.0.0.1:30301");
        assert_eq!(cfg.peers[2].index, 3);
    }
}
